### ISSUE TITLE
ImportBeforeEvent in wrong order?

### ISSUE THREAD

**Issue by featdd** [in2code-de/migration#27]
Hi,

I wanted to use the ImportBeforeEvent to manipulate some file paths before importing, but it seems the be "after" everything is already imported.

See: https://github.com/in2code-de/migration/blob/0819427ae2467bf42fb2c1d02e22c1fa7704c759/Classes/Port/Import.php#L136-L151

Pull request incoming

Greetings
Daniel

**Comment by featdd** [comment]
Hi @einpraegsam,

could you merge this or do these changes cause any problems?
(Sorry to ask again, I know it's difficult to find time for open source projects sometimes 🙈)

Greetings
Daniel

**Comment by einpraegsam** [comment]
Hi Daniel,

because this request needs more time to be tested, I still can't dug into it. 
Maybe in the upcoming weeks, because we have a paid customer project, where I need to use EXT:migration

Alex

**Comment by einpraegsam** [comment]
Fixed by merging
