### ISSUE TITLE
isAlreadyMigrated is never called

### ISSUE THREAD

**Issue by mxsteini** [in2code-de/migration#32]
Seems that isAlreadyMigrated in PropertyHelper is never called when migrating an old table to a new table.
Couldn't find any functioncall for this ...

**Comment by einpraegsam** [comment]
Please write more to your request (e.g. a link to the code can help here)

**Comment by mxsteini** [comment]
Sorry, no code.
I'm migrating an old table to a new one.
Fields _migrated* are correctly inserted.
Then I ran the migration a second time. Documentation says this is possible because the field _migrated is tested.
Since this is not working, I was searching for code which could do this. The AbstractPropertyHelper provides a method 'isAlreadyMigrated' but this method is never called while the migration.
And I couldn't find any code which is calling this method.

**Comment by einpraegsam** [comment]
Ah, I understand your confusion.
Fields with name _migrated, _migrated_uid and _migrated_table are automatically be filled on a migration run (if they exists). 
Nevertheless, there is no logic implemented that listen to values in this fields on a second run. This is only usefull if you need this. E.g. You are going to migrate a an mm table in MmMigrator.php and after that you need the old value for building relations. So you can build your own function and check _migrated_uid...
